line-length = 88
target-version = "py312"

[lint]
select = [
    "E", "W",    # pycodestyle
    "F",         # pyflakes
    "I",         # isort
    "B",         # bugbear
    "UP",        # pyupgrade
    "N",         # naming
    "SIM",       # simplifications
    "ANN",       # typing
    "TID",       # tidy imports
    "Q",         # quote consistency
]
ignore = []

[format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true